############################
## CHANGE THESE
############################

baseURL: 'https://Samba-Lab.github.io/codigoergosum'
title: Codigo Ergo Sum

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


